/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: GameDev Nick (https://sketchfab.com/GameDevNick)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/old-wooden-bookshelves-3f856846b4a144e28109aea9269aca6a
title: Old Wooden Bookshelves
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { degToRad } from "three/src/math/MathUtils";

export default function Bookshelves(props) {
  const { nodes, materials } = useGLTF("/models/old_wooden_bookshelves.glb");
  return (
    <group {...props} dispose={null} scale={0.5} rotation-y={degToRad(180)}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_4.geometry}
            material={materials.Material}
          />
          <group position={[0, 0, -4]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_6.geometry}
              material={materials.Material}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/old_wooden_bookshelves.glb");
