/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Sviatoslav Semenov (https://sketchfab.com/svyasem)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/old-wooden-bucket-7649d45e7d6f408b9b5929ab51895dfa
title: Old wooden bucket
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Bucket(props) {
  const { nodes, materials } = useGLTF("/models/old_wooden_bucket.glb");
  return (
    <group {...props} dispose={null}>
      <group position={[0, -0.5, 0]} rotation={[Math.PI / 2, -0.01, -Math.PI]}>
        <group rotation={[-Math.PI, 0, 0]}>
          <group scale={0.1}>
            <group position={[0, 0, -6.55]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Bucket__0.geometry}
                material={materials["Scene_-_Root"]}
              />
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/old_wooden_bucket.glb");


