/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Timothy Hsu (https://sketchfab.com/timothyhsu)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/fly-agaric-mushroom-d6c3876f091b4de49a38553a177bab0f
title: Fly Agaric Mushroom
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Mushroom(props) {
  const { nodes, materials } = useGLTF("/models/fly_agaric_mushroom.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.hood_low_default_0.geometry}
              material={materials["default"]}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.stem_low_default_0.geometry}
              material={materials["default"]}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.annulus_low_default_0.geometry}
              material={materials["default"]}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/fly_agaric_mushroom.glb");



