/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: GameDev Nick (https://sketchfab.com/GameDevNick)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/old-wooden-table-e53a5ef2faf84edcaddf49d4d27f366c
title: Old Wooden Table
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function OldTable(props) {
  const { nodes, materials } = useGLTF("/models/old_wooden_table.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_4.geometry}
            material={materials.Material}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/old_wooden_table.glb");

