/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { RigidBody, CuboidCollider } from "@react-three/rapier";


export default function Seat(props) {
  const { nodes, materials } = useGLTF("/models/seat.glb");
  return (
    <RigidBody type="fixed" colliders={false} position={[1.75, 0, 0]} rotation-y={-Math.PI * .75}>
      <CuboidCollider args={[0.5, 1.05, 0.6]} />
      <group {...props} dispose={null}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plano002.geometry}
          material={materials.M_Table_01}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plano002_1.geometry}
          material={materials.Materiais}
        />
      </group>
    </RigidBody>
  );
}

useGLTF.preload("/models/seat.glb");