/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Seat(props) {
  const { nodes, materials } = useGLTF("/models/seat.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plano002.geometry}
        material={materials.M_Table_01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plano002_1.geometry}
        material={materials.Materiais}
      />
    </group>
  );
}

useGLTF.preload("/models/seat.glb");