/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Mad_Lobster_Workshop (https://sketchfab.com/Mad_Lobster_Workshop)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/1800s-wooden-stools-type-a-f74c18df1a07417382a7a82d942cf760
title: 1800s Wooden Stools Type A
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Stool(props) {
  const { nodes, materials } = useGLTF("/models/1800s_wooden_stools_type_a.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-1.43, 0, -0.57]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_4.geometry}
              material={materials["1800s_Wooden_Stool_Type_A_WoodA"]}
            />
          </group>
          {/* <group position={[-0.83, 0, -0.57]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_6.geometry}
              material={materials["1800s_Wooden_Stool_Type_A_WoodB"]}
            />
          </group>
          <group position={[-0.01, 0, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_8.geometry}
              material={materials["1800s_Wooden_Stool_Type_A_WoodC"]}
            />
          </group>
          <group position={[0.71, 0, -0.57]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_10.geometry}
              material={materials["1800s_Wooden_Stool_Type_A_Painted_Blue"]}
            />
          </group>
          <group position={[1.28, 0, -0.57]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_12.geometry}
              material={materials["1800s_Wooden_Stool_Type_A_Painted_White"]}
            />
          </group> */}
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/1800s_wooden_stools_type_a.glb");
