/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Ruslan Malovsky (https://sketchfab.com/malovsky)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/ax-with-a-stump-bee3645990e14378acaad55971296629
title: Ax with a Stump
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function StumpAxe(props) {
  const { nodes, materials } = useGLTF("/models/ax_with_a_stump.glb");
  return (
    <group {...props} dispose={null}>
      <group position={[0, 12.79, 18.51]} rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group
            position={[0, 0, 565.64]}
            rotation={[-1.66, Math.PI / 2, 0]}
            scale={[16.82, 19.97, 19.97]}
          >
            <group
              position={[-17.81, 51.16, -0.6]}
              rotation={[-Math.PI / 2, Math.PI / 2, 0]}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object003_Stvol_0.geometry}
                material={materials.Stvol}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object003_Kora_0.geometry}
                material={materials.Kora}
              />
            </group>
          </group>
          <group
            position={[-69.06, 432.89, 886.33]}
            rotation={[-1.92, 0.21, -0.33]}
            scale={0.62}
          >
            <group
              position={[-0.17, 578.02, 123.47]}
              rotation={[1.55, 0, 0]}
              scale={[0.66, 1.3, 1.54]}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder003_Ryk_0.geometry}
                material={materials.material}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder003_Nak_0.geometry}
                material={materials.material_3}
              />
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/ax_with_a_stump.glb");
