/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Table(props) {
  const { nodes, materials } = useGLTF("models/table.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Círculo002.geometry}
        material={materials["wood table"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Círculo002_1.geometry}
        material={materials["Free_Kitchen_Set_13.001"]}
      />
    </group>
  );
}

useGLTF.preload("models/table.glb");