/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { CylinderCollider, RigidBody } from "@react-three/rapier";

export default function Table(props) {
  const { nodes, materials } = useGLTF("models/table.glb");
  return (
    <RigidBody type='fixed' colliders={false}>
      <CylinderCollider args={[1.8, 1.5]} />
      <group {...props} dispose={null} >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Círculo002.geometry}
          material={materials["wood table"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Círculo002_1.geometry}
          material={materials["Free_Kitchen_Set_13.001"]}
        />
      </group>
    </RigidBody>
  );
}

useGLTF.preload("models/table.glb");