/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: J0Y (https://sketchfab.com/lloydrostek)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/wooden-table-31ab9f9ad2fa425aa75e8bb76cad8fc1
title: Wooden Table
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function WoodenTable(props) {
  const { nodes, materials } = useGLTF("/models/wooden_table.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial.geometry}
            material={materials.TT_checker_512x512_UV_GRID}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_1.geometry}
            material={materials.TT_checker_512x512_UV_GRID}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_2.geometry}
            material={materials.TT_checker_512x512_UV_GRID}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_3.geometry}
            material={materials.TT_checker_512x512_UV_GRID}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_4.geometry}
            material={materials.TT_checker_512x512_UV_GRID}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_5.geometry}
            material={materials.TT_checker_512x512_UV_GRID}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/wooden_table.glb");

