/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: fangzhangmnm (https://sketchfab.com/fangzhangmnm)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/pine-forest-ece69535f7584e099488f65f2072264e
title: Pine Forest
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function PineForest(props) {
  const { nodes, materials } = useGLTF("/models/pine_forest.glb");
  return (
    <group {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="pine1_0">
                <mesh
                  name="Object_4"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_4.geometry}
                  material={materials.pine}
                />
              </group>
              <group name="obj1_1">
                <mesh
                  name="Object_6"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_6.geometry}
                  material={materials.mat1}
                />
              </group>
              <group name="obj2_2">
                <mesh
                  name="Object_8"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_8.geometry}
                  material={materials.mat2}
                />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/pine_forest.glb");
